excluded:
  - Pods
  
disabled_rules:
  - trailing_whitespace # 禁用行尾空白規則
  - comment_spacing # 禁用註釋間距規則
  - line_length # 禁用行長規則
  - cyclomatic_complexity # 禁用函數複雜度規則
  - function_body_length
  - type_body_length
  - file_length
  
identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - url
    - app
